name: Latest blog post workflow
on:
   schedule:
     # Runs every Hour
     - cron: '0 * * * *'
   workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with lastest blog posts
    runs-on: unbutu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishanar/blog-post-workflow@master
        with:
           feed_list: "https://c0d3x27.medium.com/"
